// Static database containing fallback explanations for common benchmark words

export interface WordExplanation {
  japanese: string;
  hiragana: string;
  katakana: string;
  romaji: string;
  english: string;
  hindi: string;
  simpleMeaning: string;
  detailedMeaning: string;
  wordType: string;
  jlptLevel: string;
  frequencyRank: string;
  usageRegister: string;
  commonSituations: string;
  memoryTrick: string;
  rootBreakdown: string;
  synonyms: string;
  opposites: string;
  easySentenceJa: string;
  easySentenceEn: string;
  intermediateSentenceJa: string;
  intermediateSentenceEn: string;
  advancedSentenceJa: string;
  advancedSentenceEn: string;
  realLifeUsage: string;
  commonMistakes: string;
  relatedGrammar: string;
  relatedVocabulary: string;
  pronunciationTips: string;
  culturalNotes: string;
  audioReadingText: string;
  emoji: string;
  visualAssociation: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  reviewPriority: 'High' | 'Medium' | 'Low';
  aiTutorExplanation: string;
}

export const fallbackRegistry: Record<string, WordExplanation> = {
  '食べる': {
    japanese: '食べる',
    hiragana: 'たべる',
    katakana: '',
    romaji: 'Taberu',
    english: 'To Eat',
    hindi: 'खाना (Khana)',
    simpleMeaning: 'Consuming solid food or meals.',
    detailedMeaning: 'A transitive Ichidan verb denoting the action of consuming food. It is the dictionary form and represents the baseline representation of eating.',
    wordType: 'Verb',
    jlptLevel: 'N5',
    frequencyRank: 'Top 100',
    usageRegister: 'Informal (Dictionary form)',
    commonSituations: 'Dining, meal discussions, daily schedules, restaurant settings.',
    memoryTrick: 'Taberu sounds like "Table". You sit at a table to eat food.',
    rootBreakdown: '食 (Eat/Food) + べる (conjugative suffix).',
    synonyms: '食す (Shokusu), 召し上がる (Meshiagaru - honorific), いただく (Itadaku - humble)',
    opposites: '吐き出す (Hakidasu - to spit out/vomit)',
    easySentenceJa: 'リンゴを食べる。',
    easySentenceEn: 'I eat an apple.',
    intermediateSentenceJa: '寿司を食べに行きませんか。',
    intermediateSentenceEn: 'Shall we go to eat sushi?',
    advancedSentenceJa: '健康維持のためには、バランスの良い食事を時間をかけて食べることが推奨されます。',
    advancedSentenceEn: 'For maintaining good health, it is recommended to take time and eat a well-balanced meal.',
    realLifeUsage: 'Crucial for basic interactions. Used at home, restaurants, and schools. Always used before meals in the phrase "Itadakimasu" (humbly receiving food).',
    commonMistakes: 'Do not confuse with 飲む (nomu - to drink) when talking about soup or medicine (in Japanese, medicine is "taken" as 飲む, not 食べる).',
    relatedGrammar: '〜たい (want to eat: 食べたい), 〜ながら (eat while doing: 食べながら)',
    relatedVocabulary: '食べ物 (Tabemono - food), 食堂 (Shokudō - cafeteria), 朝食 (Chōshoku - breakfast)',
    pronunciationTips: 'Accent on the second mora "be". Pronounced flatly as Ta-be-ru.',
    culturalNotes: 'Saying "Itadakimasu" before eating expresses Shinto/Buddhist gratitude to the ingredients and cook.',
    audioReadingText: 'たべる (taberu)',
    emoji: '🍎',
    visualAssociation: 'A person sitting at a wooden kitchen table enjoying a steaming bowl of ramen with chopsticks.',
    difficulty: 'Easy',
    reviewPriority: 'Low',
    aiTutorExplanation: 'こんにちは！"Taberu" is one of the very first verbs you will learn in Japanese. It is a standard Ru-verb (Ichidan), meaning you can conjugate it easily by replacing "ru" with "masu" to make it polite (Tabemasu). Keep practicing!'
  },
  '空港': {
    japanese: '空港',
    hiragana: 'くうこう',
    katakana: '',
    romaji: 'Kūkō',
    english: 'Airport',
    hindi: 'हवाई अड्डा (Hawai Adda)',
    simpleMeaning: 'A place where airplanes land and take off.',
    detailedMeaning: 'A noun composed of kanji meaning "sky" and "harbor". Refers to an aviation terminal facility.',
    wordType: 'Noun',
    jlptLevel: 'N4',
    frequencyRank: 'Top 500',
    usageRegister: 'Neutral / Formal',
    commonSituations: 'Travel conversations, booking tickets, flight status reports.',
    memoryTrick: 'Kūkō starts with "Kū" (air/vacuum). Think of cooling off in the sky harbor.',
    rootBreakdown: '空 (Sky/Air) + 港 (Harbor/Port). Sky harbor!',
    synonyms: '飛行場 (Hikōjō - airfield), エアポート (Eapōto - loanword)',
    opposites: '港 (Minato - sea harbor)',
    easySentenceJa: '空港は広いです。',
    easySentenceEn: 'The airport is wide.',
    intermediateSentenceJa: '明日、成田空港へ友達を迎えに行きます。',
    intermediateSentenceEn: 'Tomorrow, I will go to Narita Airport to pick up my friend.',
    advancedSentenceJa: '国際線の搭乗手続きは、通常出発予定時刻の二時間前までに空港で完了する必要があります。',
    advancedSentenceEn: 'International boarding procedures generally must be completed at the airport at least two hours prior to the scheduled departure time.',
    realLifeUsage: 'In travel guides, station announcements, and tourist conversations.',
    commonMistakes: 'Make sure to double the "o" vowel sound: read as Kū-kō (long vowels), not Kuko.',
    relatedGrammar: '〜へ行く (go to airport: 空港へ行く), 〜で待つ (wait at airport: 空港で待つ)',
    relatedVocabulary: '飛行機 (Hikōki - airplane), 搭乗券 (Tōjōken - boarding pass), 免税店 (Menzeiten - duty-free shop)',
    pronunciationTips: 'Elongate both syllables: Koo-koo.',
    culturalNotes: 'Narita and Haneda airports are the key gateways to Tokyo and feature traditional cultural exhibits inside.',
    audioReadingText: 'くうこう (kūko)',
    emoji: '✈️',
    visualAssociation: 'A massive modern glass terminal building with a jumbo jet visible on the runway under a clear blue sky.',
    difficulty: 'Easy',
    reviewPriority: 'Medium',
    aiTutorExplanation: 'Let\'s learn "Kūkō"! Think of it etymologically: 空 means sky, and 港 means harbor. Together, they form "sky port" or airport! Super logical, right?'
  },
  'ヤバい': {
    japanese: 'ヤバい',
    hiragana: 'やばい',
    katakana: 'ヤバい',
    romaji: 'Yabai',
    english: 'Dangerous / Amazing / Crazy (intensifier)',
    hindi: 'अद्भुत / खतरनाक',
    simpleMeaning: 'Originally "dangerous," now used to mean "crazy good" or "terrible" depending on context.',
    detailedMeaning: 'A highly colloquial i-adjective that has transitioned from underworld slang meaning "perilous" to a modern youth intensifier representing extreme states (good or bad).',
    wordType: 'Adjective',
    jlptLevel: 'N2',
    frequencyRank: 'Top 100 in speech',
    usageRegister: 'Highly Informal / Slang',
    commonSituations: 'Casual chat, anime dialogues, reacting to surprise, enjoying delicious food.',
    memoryTrick: 'Yabai sounds like "Yeah Bye". If something is dangerous, you say "Yeah, Bye!" and run.',
    rootBreakdown: 'Originally written in kanji 厄場 (dangerous place) + adjective suffix い.',
    synonyms: 'すごい (Sugoi - amazing), 危険な (Kiken na - dangerous)',
    opposites: '普通 (Futsuu - ordinary/normal)',
    easySentenceJa: 'これ、ヤバい！',
    easySentenceEn: 'This is crazy/amazing!',
    intermediateSentenceJa: '明日テストなのに勉強してない。ヤバいなぁ。',
    intermediateSentenceEn: 'I have a test tomorrow but haven\'t studied. I\'m in trouble (it\'s bad).',
    advancedSentenceJa: '若者の間で「ヤバい」という言葉は、否定的評価のみならず、最上級の賛辞としても多用されている。',
    advancedSentenceEn: 'Among youth, the word "yabai" is frequently utilized not only for negative evaluation but also as a superlative compliment.',
    realLifeUsage: 'Everywhere in casual youth conversations. When eating delicious food, Japanese youth say "Yabai!" to mean "This tastes amazing!"',
    commonMistakes: 'Never use in formal business meetings or with superiors (teachers, bosses). It sounds unpolished.',
    relatedGrammar: 'ヤバすぎる (yabasugiru - way too crazy/extreme)',
    relatedVocabulary: 'マジで (Maji de - seriously), チョー (Chō - super/very)',
    pronunciationTips: 'Pitch accent falls on the middle "ba". Pronounced Ya-ba-i.',
    culturalNotes: 'Yabai is a linguistic phenomenon representing semantic shift where a negative term becomes a positive modifier, similar to "sick" or "wicked" in English.',
    audioReadingText: 'やばい (yabai)',
    emoji: '💥',
    visualAssociation: 'A youth with a shocked face looking at an incredibly delicious, towering burger, exclaiming with sparkles around them.',
    difficulty: 'Medium',
    reviewPriority: 'High',
    aiTutorExplanation: 'Haha, "Yabai" is extremely popular! But remember, context is king! If you look worried, it means "I\'m in trouble." If you smile, it means "This is awesome!"'
  },
  '鬱': {
    japanese: '鬱',
    hiragana: 'うつ',
    katakana: '',
    romaji: 'Utsu',
    english: 'Depression / Melancholy',
    hindi: 'अवसाद / निराशा',
    simpleMeaning: 'Feeling down, melancholy, or clinically depressed.',
    detailedMeaning: 'A noun representing mental depression or gloominess. Known orthographically for having 29 strokes, representing one of the most complex standard characters.',
    wordType: 'Noun',
    jlptLevel: 'N1',
    frequencyRank: 'Top 1500',
    usageRegister: 'Medical / Formal / Colloquial (as 鬱になる)',
    commonSituations: 'Psychology, medicine, expressing seasonal blues, feeling heavy.',
    memoryTrick: '29 strokes! Writing this kanji is so difficult it might make you feel depressed!',
    rootBreakdown: '木 (wood) + 缶 (can) + 木 (wood) + 𣎴 (stand) + 鬯 (herb/wine) + 彡 (hair/feathers). Depicts dense forest and herbs for medicine.',
    synonyms: '憂鬱 (Yūutsu - melancholy), 落ち込み (Ochikomi - feeling down)',
    opposites: '元気 (Genki - energetic/cheerful), 陽気 (Yōki - lively)',
    easySentenceJa: '雨の日は鬱になる。',
    easySentenceEn: 'Rainy days make me feel depressed.',
    intermediateSentenceJa: '仕事のストレスで鬱病になりました。',
    intermediateSentenceEn: 'I developed clinical depression due to work stress.',
    advancedSentenceJa: '現代社会における鬱病の増加は、複雑な人間関係や過度な情報量が一因であると指摘されている。',
    advancedSentenceEn: 'It has been pointed out that the increase of depression in modern society is partially caused by complex human relationships and excessive amounts of information.',
    realLifeUsage: 'Often used colloquially in casual speech as "鬱だ" (Utsu da - I feel depressed/gloomy) during stressful times.',
    commonMistakes: 'Do not attempt to write the kanji unless you have practiced the complex stroke order. Most Japanese write it in Hiragana (うつ) in casual texts.',
    relatedGrammar: '〜になる (to become depressed: 鬱になる)',
    relatedVocabulary: '鬱病 (Utsubyō - clinical depression), 憂鬱 (Yūutsu - gloominess)',
    pronunciationTips: 'Start high and drop: U-tsu.',
    culturalNotes: 'Mental health discussions are historically sensitive in Japan, but dialogue around "Utsu" has become mainstream due to corporate stress awareness.',
    audioReadingText: 'うつ (utsu)',
    emoji: '🌧️',
    visualAssociation: 'A person looking out a window on a grey, rainy afternoon, head resting on their hands.',
    difficulty: 'Hard',
    reviewPriority: 'High',
    aiTutorExplanation: 'Oh, "Utsu" has a very complex kanji! Don\'t stress too much about writing it by hand — even native speakers type it or write it in Hiragana. Keep your chin up!'
  },
  '偶然': {
    japanese: '偶然',
    hiragana: 'ぐうぜん',
    katakana: '',
    romaji: 'Gūzen',
    english: 'Coincidence / By chance',
    hindi: 'इत्तेफाक (Ittefaq)',
    simpleMeaning: 'Something happening by pure luck or coincidence without a plan.',
    detailedMeaning: 'A noun and adverbial noun representing coincidental occurrences or random events.',
    wordType: 'Adverb',
    jlptLevel: 'N3',
    frequencyRank: 'Top 800',
    usageRegister: 'Neutral / Formal',
    commonSituations: 'Meeting friends unexpectedly on the street, matching schedules, random luck.',
    memoryTrick: 'Gūzen sounds like "Gozen" (morning). Imagine meeting your friend by pure coincidence in the morning.',
    rootBreakdown: '偶 (Accidental/Unexpected) + 然 (State of being). State of accidental occurrence.',
    synonyms: 'たまたま (Tamatama - by chance), 奇遇 (Kigū - coincidence)',
    opposites: '必然 (Hitsuzen - necessity/inevitable), 故意 (Koi - intentional)',
    easySentenceJa: '偶然ですね！',
    easySentenceEn: 'What a coincidence!',
    intermediateSentenceJa: '駅で偶然高校の同級生に会いました。',
    intermediateSentenceEn: 'I ran into a high school classmate at the station by coincidence.',
    advancedSentenceJa: '科学的発見の多くは、実験中の偶然の失敗や予想外の現象から生まれることが多い。',
    advancedSentenceEn: 'Many scientific discoveries are born from coincidental failures or unexpected phenomena during experiments.',
    realLifeUsage: 'Commonly said when running into a friend unexpectedly: "Gūzen dane!" (What a coincidence!)',
    commonMistakes: 'To use as an adverb, append に (Gūzen ni - by chance), e.g., 偶然に会う.',
    relatedGrammar: '偶然に (Adverbial form), 偶然の (Adjectival modifier)',
    relatedVocabulary: '必然 (Hitsuzen - inevitability), 運命 (Unmei - destiny)',
    pronunciationTips: 'Elongate the first syllable: Goo-zen.',
    culturalNotes: 'Meeting someone unexpectedly in Japan is often linked to "En" (縁 - karmic connection or fate).',
    audioReadingText: 'ぐうぜん (gūzen)',
    emoji: '🎲',
    visualAssociation: 'Two friends waving in surprise as they bump into each other in front of a crossing gate.',
    difficulty: 'Medium',
    reviewPriority: 'Medium',
    aiTutorExplanation: 'Hi! "Gūzen" is a great word. When you run into someone unexpectedly, you can look surprised and say "Gūzen desu ne!" It sounds natural and friendly!'
  },
  '挨拶': {
    japanese: '挨拶',
    hiragana: 'あいさつ',
    katakana: '',
    romaji: 'Aisatsu',
    english: 'Greeting',
    hindi: 'अभिवादन (Abhivaadan)',
    simpleMeaning: 'Greeting someone (e.g. hello, goodbye).',
    detailedMeaning: 'A noun or Suru-verb denoting the act of greeting, acknowledging, or paying respects to someone.',
    wordType: 'Noun',
    jlptLevel: 'N4',
    frequencyRank: 'Top 200',
    usageRegister: 'Formal / Informal',
    commonSituations: 'Everyday encounters, morning office arrivals, school greetings.',
    memoryTrick: '"Aisatsu" sounds like "Eye sat sue". Eye sat and greeted Sue.',
    rootBreakdown: '挨 (approach/push) + 拶 (draw near). Approaching and drawing near to someone to greet them!',
    synonyms: '挨拶回り (Aisatsumawari), 会釈 (Eshaku)',
    opposites: '無視 (Mushi - ignoring)',
    easySentenceJa: '毎朝、挨拶をします。',
    easySentenceEn: 'I greet people every morning.',
    intermediateSentenceJa: '日本社会では、挨拶は非常に重要なマナーとされています。',
    intermediateSentenceEn: 'In Japanese society, greetings are considered extremely important etiquette.',
    advancedSentenceJa: '新入社員は、他部署を回って自己紹介を兼ねた挨拶回りを行うのが通例である。',
    advancedSentenceEn: 'It is customary for new employees to visit other departments to make greetings that also serve as self-introductions.',
    realLifeUsage: 'A fundamental social pillar in Japan. Morning briefings (chourei) always begin with a unified greeting.',
    commonMistakes: 'Avoid ignoring greetings (called "aisatsu-mushi"), which is highly offensive in work and school environments.',
    relatedGrammar: '〜をする (to greet: 挨拶をする)',
    relatedVocabulary: '自己紹介 (Jikoshoukai - self introduction), 礼儀 (Reigi - manners)',
    pronunciationTips: 'Pronounced as Ai-sa-tsu with a slight drop in pitch on "tsu".',
    culturalNotes: 'Aisatsu is not just hello; it encompasses bowing and showing respect, reflecting deep Shinto/social harmony.',
    audioReadingText: 'あいさつ (aisatsu)',
    emoji: '🙇',
    visualAssociation: 'Two corporate employees bowing to each other at a 15-degree angle in a sunlit modern lobby.',
    difficulty: 'Easy',
    reviewPriority: 'Medium',
    aiTutorExplanation: 'Hello! "Aisatsu" is a beautiful concept. In Japan, greeting others warmly isn\'t just polite—it sets the tone for harmony (Wa) in the entire workspace. Always greet your colleagues with a smile and a bow!'
  },
  '準備': {
    japanese: '準備',
    hiragana: 'じゅんび',
    katakana: '',
    romaji: 'Junbi',
    english: 'Preparation',
    hindi: 'तैयारी (Taiyaari)',
    simpleMeaning: 'Getting ready or preparing for something.',
    detailedMeaning: 'A noun or Suru-verb denoting the act of preparing, making arrangements, or getting things ready beforehand.',
    wordType: 'Noun',
    jlptLevel: 'N4',
    frequencyRank: 'Top 300',
    usageRegister: 'Formal / Informal',
    commonSituations: 'Meetings, exams, travels, cooking, event planning.',
    memoryTrick: '"Junbi" sounds like "June Bee". Bees prepare for summer in June!',
    rootBreakdown: '準 (standard/semi) + 備 (equip/provide). Setting standards and equipping yourself!',
    synonyms: '用意 (Yōi), 支度 (Shitaku)',
    opposites: '本番 (Honban - the real performance), 片付け (Katadzuke - cleaning up)',
    easySentenceJa: '旅行の準備をする。',
    easySentenceEn: 'I prepare for the trip.',
    intermediateSentenceJa: '会議に必要な資料の準備が終わりました。',
    intermediateSentenceEn: 'The preparation of documents required for the meeting is finished.',
    advancedSentenceJa: '災害発生時に備えて、避難経路の確認や非常食の準備を怠らないようにすべきだ。',
    advancedSentenceEn: 'To prepare for a disaster, one should not neglect checking evacuation routes and preparing emergency food supplies.',
    realLifeUsage: 'Extremely common in project management, school tests, cooking preparation (shitaku/junbi), and daily reminders.',
    commonMistakes: 'Do not confuse with "Yōi" which is used for immediate prep (like "Ready, set, go!" - Yōi, don!), while "Junbi" is for long-term preparations.',
    relatedGrammar: '〜の準備ができる (preparation is ready)',
    relatedVocabulary: '予習 (Yoshū - preparing for lessons), 備蓄 (Bichiku - stockpiling)',
    pronunciationTips: 'Even stress: Jun-bi. Do not shorten to Jubi.',
    culturalNotes: 'The Japanese place extreme value on "Dandori" (prior planning) and thorough preparation to ensure events run smoothly.',
    audioReadingText: 'じゅんび (junbi)',
    emoji: '🎒',
    visualAssociation: 'A student carefully sorting books, notebooks, and pencils into their backpack the night before school.',
    difficulty: 'Easy',
    reviewPriority: 'Medium',
    aiTutorExplanation: 'Let\'s learn "Junbi"! Whether you are preparing for a trip or studying for the JLPT, doing "Junbi" properly guarantees success. Make sure to use the verb form "junbi suru" in daily conversations!'
  }
};
